trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Environment variables from your actual files
  NUXT_SESSION_PASSWORD: '$(NUXT_SESSION_PASSWORD)'
  DATABASE_URL: '$(DATABASE_URL)'
  RESEND_API_KEY: '$(RESEND_API_KEY)'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g pnpm
    pnpm install --frozen-lockfile
    pnpm run build
  displayName: 'Build application'
  env:
    NUXT_SESSION_PASSWORD: $(NUXT_SESSION_PASSWORD)
    DATABASE_URL: $(DATABASE_URL)
    RESEND_API_KEY: $(RESEND_API_KEY)

- task: CopyFiles@2
  inputs:
    sourceFolder: 'apps/web/.output/public'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build output'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish artifacts'
