trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Add your environment variables here
  NUXT_SESSION_PASSWORD: '$(NUXT_SESSION_PASSWORD)'
  STRAPI_URL: '$(STRAPI_URL)'
  STRAPI_API_TOKEN: '$(STRAPI_API_TOKEN)'
  # Add any other environment variables your app needs

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g pnpm
    pnpm install --frozen-lockfile
    pnpm run build
  displayName: 'Build application'
  env:
    NUXT_SESSION_PASSWORD: $(NUXT_SESSION_PASSWORD)
    STRAPI_URL: $(STRAPI_URL)
    STRAPI_API_TOKEN: $(STRAPI_API_TOKEN)
    # Add any other environment variables here too

- task: CopyFiles@2
  inputs:
    sourceFolder: 'apps/web/.output/public'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build output'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish artifacts'
